version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: collaborate
      DB_PASSWORD: collaborate_password
      DB_NAME: collaborate_db
      APP_ENV: development

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: collaborate_db
      MYSQL_USER: collaborate
      MYSQL_PASSWORD: collaborate_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./collaborate_db.sql:/docker-entrypoint-initdb.d/collaborate_db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - db

volumes:
  db_data: 