services:
  - type: web
    name: collaborate
    env: docker
    repo: https://github.com/saurabhdubeyy/Collaborate.git # Updated with correct repository
    region: ohio
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: collaborate-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: collaborate-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: collaborate-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: collaborate-db
          property: password
      - key: APP_ENV
        value: production
    domains:
      - collaborate-app.onrender.com # This will be assigned by Render

databases:
  - name: collaborate-db
    plan: free
    region: ohio
    databaseName: collaborate_db
    user: postgres 