services:
  - type: web
    name: collaborate
    env: docker
    repo: https://github.com/saurabhdubeyy/Collaborate.git
    region: ohio
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      # Using Render's internal env vars for PostgreSQL database
      - key: PGHOST
        fromDatabase:
          name: collaborate-db
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: collaborate-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: collaborate-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: collaborate-db
          property: password
      - key: PGPORT
        fromDatabase:
          name: collaborate-db
          property: port
    domains:
      - collaborate-app.onrender.com

databases:
  - name: collaborate-db
    plan: free
    region: ohio
    databaseName: collaborate_db 